AllCops:
  EnabledByDefault: true
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://github.com/voxable-labs/voxable-style-guide
  
# Force table-style hash alignment.
Layout/AlignHash:
  EnforcedColonStyle: table
  
# Force equal sign alignment.
Layout/ExtraSpacing:
  ForceEqualSignAlignment: true
  
# Don't require copyright notices
Style/Copyright:
  Enabled: false
  
# Prefer keyword arguments to options hashes
# https://github.com/voxable-labs/ruby-style-guide#no-optional-hash-params
Style/OptionHash:
  Enabled: true

# --||----------------------
#   || Rails
# ==||======================

# Don't measure class length for controllers.
Metrics/ClassLength:
  Exclude:
    - ./app/bots/messenger_bot/controllers/**/*.rb

# Don't require documentation for ActiveRecord migrations.
Style/DocumentationMethod:
  Exclude:
    - db/migrate/*.rb

# --||----------------------
#   || RSpec
# ==||======================

# Ignore block length in RSPec.
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    

# Exclude hg blocks.
Metrics/BlockLength:
  ExcludedMethods:
    - class_methods
    - dynamic
    - gallery

# Use braces for block delimiters in RSpec.
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect

# Ignore absence of method call parentheses in RSpec and gemspecs,
# and ignore Heliogram methods.
Style/MethodCallWithArgsParentheses:
  Exclude:
    - spec/**/*.rb
    - ./*.gemspec
  IgnoredMethods:
    - require
    - raise
    - button
    - card
    - gallery
    - before_handler
